import React from 'react';
import { ScreenType, UserAssessmentSummary } from '../types';
import { Sidebar } from './Sidebar';

interface LearningPathScreenProps {
  onNavigate: (screen: ScreenType) => void;
  assessmentSummary?: UserAssessmentSummary;
  topicTitle?: string;
}

export const LearningPathScreen: React.FC<LearningPathScreenProps> = ({
  onNavigate,
  assessmentSummary,
  topicTitle = "Basic Circuits & Ohm's Law",
}) => {
  const score = assessmentSummary?.scorePercent ?? 80;
  const isMasteredQuiz = score >= 75;

  // Dynamically constructed roadmap nodes based on assessment
  const nodes = [
    {
      id: 'n1',
      title: 'Circuit Fundamentals: Charge, Voltage & Current',
      status: 'mastered',
      icon: 'bolt',
      info: '100% Mastery • Completed with verified potential difference intuition.',
    },
    {
      id: 'n2',
      title: "Ohm's Law & Resistance Constraints (I = V / R)",
      status: isMasteredQuiz ? 'mastered' : 'needs_review',
      icon: isMasteredQuiz ? 'verified' : 'psychology',
      info: isMasteredQuiz
        ? `Scored ${score}% in assessment • Mathematical relations verified.`
        : `Scored ${score}% • Needs review: ${assessmentSummary?.recommendedRevision || 'Inverse Proportionality'}`,
    },
    ...(assessmentSummary && assessmentSummary.weakAreas.length > 0
      ? [
          {
            id: 'n_adaptive',
            title: `Adaptive Remediation: ${assessmentSummary.recommendedRevision}`,
            status: 'in_progress',
            icon: 'auto_awesome',
            info: 'Interactive water pipe simulation & guided targeted exercises.',
            isAdaptiveRemediation: true,
          },
        ]
      : []),
    {
      id: 'n3',
      title: 'Electrical Power & Joule Heating (P = V · I = I²R)',
      status: isMasteredQuiz ? 'in_progress' : 'upcoming',
      icon: 'electric_meter',
      info: isMasteredQuiz ? 'Active next module • Estimated 15 minutes' : 'Unlocks after mastering Ohm’s Law',
    },
    {
      id: 'n4',
      title: 'Series & Parallel Resistor Networks',
      status: 'upcoming',
      icon: 'device_hub',
      info: 'Equivalent resistance, Kirchhoff’s Current & Voltage Laws (KCL / KVL)',
    },
    {
      id: 'n5',
      title: 'Capacitive & Inductive Transients in AC Circuits',
      status: 'upcoming',
      icon: 'tune',
      info: 'Time constants (τ = RC), phase angles, and reactance calculations.',
    },
  ];

  const masteredCount = nodes.filter((n) => n.status === 'mastered').length;
  const totalCount = nodes.length;
  const progressPercent = Math.round((masteredCount / totalCount) * 100);

  return (
    <div className="bg-[#faf8ff] text-[#131b2e] flex min-h-[calc(100vh-65px)] w-full font-sans">
      {/* Sidebar Navigation */}
      <Sidebar currentScreen="path" onNavigate={onNavigate} dark={false} />

      {/* Main Content */}
      <div className="flex-1 flex flex-col p-4 md:p-8 max-w-5xl mx-auto w-full pb-20 md:pb-8">
        {/* Header Hero */}
        <div className="bg-white border border-[#c7c4d7]/60 rounded-3xl p-6 md:p-8 shadow-sm mb-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#f2f3ff] border border-[#c7c4d7]/70 text-[#4648d4] text-xs font-bold mb-2">
              <span className="material-symbols-outlined text-[16px]">alt_route</span>
              Dynamic Adaptive Roadmap
            </div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-[#131b2e] tracking-tight">
              Curriculum: {topicTitle}
            </h1>
            <p className="text-sm text-[#464554] mt-1">
              Personalized syllabus generated by Nova. Updates in real-time as you complete lessons & quizzes.
            </p>
          </div>

          {/* Progress Tracker */}
          <div className="w-full md:w-64 bg-[#f2f3ff] p-4 rounded-2xl border border-[#c7c4d7]/50">
            <div className="flex justify-between text-xs font-bold mb-1.5">
              <span className="text-[#131b2e]">Curriculum Progress</span>
              <span className="text-[#4648d4]">{progressPercent}% Complete</span>
            </div>
            <div className="w-full h-3 bg-white rounded-full overflow-hidden border border-[#c7c4d7]/40">
              <div
                className="h-full bg-gradient-to-r from-[#4648d4] to-[#8B5CF6] rounded-full transition-all duration-700"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
            <div className="flex justify-between text-[11px] text-[#464554] mt-2">
              <span>{masteredCount}/{totalCount} Modules Mastered</span>
              <span>{totalCount - masteredCount} Remaining</span>
            </div>
          </div>
        </div>

        {/* Timeline Path Container */}
        <div className="bg-white border border-[#c7c4d7]/60 rounded-3xl p-6 md:p-8 shadow-sm mb-6">
          <div className="flex items-center justify-between mb-8 pb-4 border-b border-[#c7c4d7]/40">
            <h2 className="font-bold text-lg text-[#131b2e] flex items-center gap-2">
              <span className="material-symbols-outlined text-[#4648d4]">timeline</span>
              Milestone Sequence
            </h2>
            <span className="text-xs text-[#4648d4] font-bold bg-[#f2f3ff] px-3 py-1 rounded-full border border-[#c7c4d7]/50">
              Auto-adapts after every quiz
            </span>
          </div>

          {/* Vertical Timeline Layout */}
          <div className="relative pl-6 md:pl-8 border-l-2 border-[#eaedff] ml-3 md:ml-4 space-y-8">
            {nodes.map((node, idx) => {
              const isMastered = node.status === 'mastered';
              const isInProgress = node.status === 'in_progress';
              const isNeedsReview = node.status === 'needs_review';
              const isUpcoming = node.status === 'upcoming';

              return (
                <div key={node.id} className="relative group">
                  {/* Timeline Point Icon */}
                  <div
                    className={`absolute -left-[37px] md:-left-[45px] top-1 w-9 h-9 md:w-10 md:h-10 rounded-full flex items-center justify-center border-4 border-white shadow-sm transition-transform ${
                      isMastered
                        ? 'bg-emerald-500 text-white'
                        : isInProgress
                        ? 'bg-[#4648d4] text-white ai-glow scale-110'
                        : isNeedsReview
                        ? 'bg-amber-500 text-white'
                        : 'bg-[#eaedff] text-[#464554]'
                    }`}
                  >
                    <span className="material-symbols-outlined text-[18px] md:text-[20px]">
                      {node.icon}
                    </span>
                  </div>

                  {/* Node Content Card */}
                  <div
                    onClick={() => {
                      if (node.isAdaptiveRemediation) {
                        onNavigate('adaptive');
                      } else if (isInProgress || isMastered || isNeedsReview) {
                        onNavigate('classroom');
                      }
                    }}
                    className={`p-5 rounded-2xl border transition-all ${
                      node.isAdaptiveRemediation
                        ? 'bg-amber-50/80 border-amber-400 shadow-md cursor-pointer hover:bg-amber-100/70'
                        : isInProgress
                        ? 'bg-[#f2f3ff] border-[#4648d4] shadow-md cursor-pointer hover:border-[#6b38d4]'
                        : isMastered
                        ? 'bg-white border-[#c7c4d7]/50 hover:bg-[#faf8ff] cursor-pointer'
                        : isNeedsReview
                        ? 'bg-amber-50/50 border-amber-300 hover:bg-amber-50 cursor-pointer'
                        : 'bg-white/60 border-[#c7c4d7]/40 opacity-75'
                    }`}
                  >
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                      <div className="flex items-center gap-2.5">
                        <span className="text-xs font-bold text-[#464554]">
                          Step {idx + 1}
                        </span>
                        <h3
                          className={`font-bold text-base ${
                            node.isAdaptiveRemediation
                              ? 'text-amber-900'
                              : isInProgress
                              ? 'text-[#4648d4]'
                              : 'text-[#131b2e]'
                          }`}
                        >
                          {node.title}
                        </h3>
                      </div>

                      {/* Status Tag */}
                      {isMastered && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-700 bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200">
                          <span className="material-symbols-outlined text-[14px]">verified</span>
                          Mastered
                        </span>
                      )}
                      {isInProgress && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-bold text-white bg-[#4648d4] px-2.5 py-0.5 rounded-full shadow-sm">
                          <span className="material-symbols-outlined text-[14px] animate-spin">sync</span>
                          In Progress
                        </span>
                      )}
                      {isNeedsReview && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-bold text-amber-800 bg-amber-100 px-2.5 py-0.5 rounded-full border border-amber-300">
                          <span className="material-symbols-outlined text-[14px]">priority_high</span>
                          Needs Review
                        </span>
                      )}
                      {isUpcoming && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-medium text-[#464554] bg-[#eaedff] px-2.5 py-0.5 rounded-full">
                          <span className="material-symbols-outlined text-[14px]">lock</span>
                          Locked
                        </span>
                      )}
                    </div>

                    <p className="text-xs text-[#464554] mb-3">{node.info}</p>

                    {isInProgress && (
                      <div className="flex items-center justify-between pt-2 border-t border-[#4648d4]/20">
                        <span className="text-xs text-[#4648d4] font-medium">Ready to continue</span>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            if (node.isAdaptiveRemediation) {
                              onNavigate('adaptive');
                            } else {
                              onNavigate('classroom');
                            }
                          }}
                          className="px-4 py-1.5 bg-[#4648d4] hover:bg-[#6063ee] text-white text-xs font-bold rounded-lg shadow-sm flex items-center gap-1 cursor-pointer"
                        >
                          {node.isAdaptiveRemediation ? 'Launch Simulation' : 'Resume Lesson'}
                          <span className="material-symbols-outlined text-[16px]">play_arrow</span>
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
};
